---
kind: pipeline
name: default
type: docker

steps:
  - name: push
    image: appleboy/drone-git-push'
    settings:
      branch: develop
      remote: git@gitee.com:ibopo/mootdx.git
      force: false
      commit: true
      ssh_key:
        from_secret: ssh_key

