---
kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: mootdx:ci
    commands:
      - pip install -r requirements.txt -r tests/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install -U tdxpy
      - pytest -v tests

  # https://plugins.drone.io/plugins/git-push
#  - name: push_github
#    image: appleboy/drone-git-push'
#    settings:
#      branch: develop
#      remote: git@github.com:mootdx/mootdx.git
#      force: false
#      commit: false
#      ssh_key:
#        from_secret: ssh_key

  - name: push
    image: appleboy/drone-git-push'
    settings:
      branch: develop
      remote: git@gitee.com:ibopo/mootdx.git
      force: false
      commit: false
      ssh_key:
        from_secret: ssh_key

     # https://plugins.drone.io/plugins/github-release
#  - name: publish
#    image: plugins/github-release
#    settings:
#      api_key:
#        from_secret: github_apikey
#      files: dist/*
#    when:
#      event:
#        - promote
#      target:
#        - production

#  # https://plugins.drone.io/plugins/dingtalk-message
#  - name: dingtalk
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token
#      type: markdown
#    when:
#      event:
#        - promote
#      target:
#        - production
#
#  # https://plugins.drone.io/plugins/ssh
#  - name: ssh
#    image: appleboy/drone-ssh
#    settings:
#      host:
#        - example1.com
#        - example2.com
#      username: ubuntu
#      password:
#        from_secret: ssh_password
#      port: 22
#      command_timeout: 2m
#      script:
#        - echo "Hello World"
#    when:
#      event:
#        - promote
#      target:
#        - production
#
#  # https://plugins.drone.io/plugins/pypi
#  - name: pypi
#    image: plugins/pypi
#    settings:
#      username: __token__
#      password:
#        from_secret: pypi_password
#    when:
#      event:
#        - promote
#      target:
#        - production
#
#  # https://plugins.drone.io/plugins/ansible
#  - name: check ansible syntax
#    image: plugins/ansible:3
#    settings:
#      playbook: ansible/playbook.yml
#      galaxy: ansible/requirements.yml
#      inventory: ansible/inventory
#      syntax_check: true
#    when:
#      event:
#        - promote
#      target:
#        - production
#
#  - name: sync
#    image: mootdx:ci
#    environment:
#      SSH_KEY:
#        from_secret: ssh_key
#    commands:
#      - echo "$SSH_KEY" > ~/.ssh/id_rsa
#      - git remote add github git@github.com:mootdx/mootdx.git
#      - git remote add gitee git@gitee.com:ibopo/mootdx.git
#      - git checkout develop
#      - git pull gitee develop
#      - git push gitee develop
#      - git pull github develop
#      - git push github develop
#    when:
#      event:
#        - promote
#      target:
#        - development

  - name: publish
    image: mootdx:ci
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - make history USERNAME=$USERNAME PASSWORD=$PASSWORD
      - make publish USERNAME=$USERNAME PASSWORD=$PASSWORD
    when:
      event:
        - promote
      target:
        - production
