---
kind: pipeline
name: default

steps:
  - name: test
    image: mootdx:ci
    commands:
      - pip install -r requirements.txt -r tests/requirements.txt
      - pip install tdxpy
      - pytest -v
