---
kind: pipeline
name: default

steps:
  - name: test
    image: mootdx:ci
    commands:
      - pip install -r requirements.txt -r tests/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install -U tdxpy
      - pytest -v
